### ISSUE TITLE
Add option to prefer last valid IP in comma-delimited header value, not first

### ISSUE THREAD

**Issue by jstangroome** [un33k/node-ipware#2]
It appears the code currently recognises that a request header like `X-Forwarded-For` may have a comma-delimited list of IP addresses and will return the left-most valid routable IP address from the list.

However, as these headers are subject to spoofing, often it is only the right-most IP address in the list that can be trusted (because the proxy responsible for adding the right-most value is the only trusted proxy).

Perhaps introduce a config setting or optional argument that would cause a list to be processed right-to-left instead.

**Comment by un33k** [comment]
Good idea. I'll welcome a pull request or will push it up on next revision.

**Comment by un33k** [comment]
Implemented. 

var ip_info = get_ip(req, right_most_proxy=True)
