### ISSUE TITLE
Only one type of IP

### ISSUE THREAD

**Issue by robertstefan** [un33k/node-ipware#7]
The server where I'm running node doesn't have support for IPv6; ergo the result address is always prefixed by `::ffff:`.
Is there a way to get only the IPv4 address ?

Thank you.

**Comment by un33k** [comment]
If there is no IPv6, it should automatically return you IPv4.

**Comment by robertstefan** [comment]
Agreed, but unfortunately, I always get `::ffff:`. :(

**Comment by un33k** [comment]
If you are behind a proxy server (AWS ELB, Nginx .etc), see which header you are getting. Then adjust the IPWARE_HTTP_HEADER_PRECEDENCE_ORDER to reflect that.

**Comment by robertstefan** [comment]
Thanks. I will take a look at it asap and I'll come back with a reply if anything wrong.

**Comment by robertstefan** [comment]
So, I finally was able to get the time to implement the changes that you specified.
But, I have the following conclusions:

- the leading `::ffff:` of the IP address is present all the time;
- running this package with `sailsjs` in AWS fails to return the correct IP address, even though the `IPWARE_HTTP_HEADER_PRECEDENCE_ORDER` has been configured [somehow it only returns the Nginx IP address];
- testing on the local machine however, everything was perfect;

Maybe there is something I missed, maybe something else; have no idea. Unfortunately, i had to remove the package from the project, but in the end it did help me to implement the logic directly into the project.

**Comment by un33k** [comment]
ipware is at the mercy of the upstream proxy server. In other words, it can only return the ip address that has been passed down by the proxy server. 

You want to take version 0.0.8 for a spin as it now supports hyphenated header keys.
